### ISSUE TITLE
Code compiled with error

### ISSUE THREAD

**Issue by Vibatious** [open-roboclub/roboclub-vue#220]
![Screenshot 2019-04-03 at 7 10 41 PM](https://user-images.githubusercontent.com/22557718/55483969-3f862980-5645-11e9-9744-abb8f7a8b860.png)

![Screenshot 2019-04-03 at 7 19 38 PM](https://user-images.githubusercontent.com/22557718/55484458-29c53400-5646-11e9-8844-dd5ab2e034da.png)

**Comment by Haider8** [comment]
@iamareebjamal Do we have to solve these issues manually. I find that ```yarn run lint --fix``` is of no help here.

**Comment by iamareebjamal** [comment]
@Haider8 Disable vue/html-indent and other lints which are causing problems
