### ISSUE TITLE
Vertically misaligned footer items

### ISSUE THREAD

**Issue by roshnet** [open-roboclub/roboclub-vue#245]
![Screenshot_2019-05-08-15-23-42-925_com android chrome](https://user-images.githubusercontent.com/40719199/57367411-8a481380-71a6-11e9-9a41-00fb37944975.png)

In the footer, the `Developers` names are vertically misaligned, as observed on mobile screen size.
PS: the Facebook icon can be brought down and centred with other two icons.

**Comment by Crouser** [comment]
@Haider8 i would like to worl on this issue.

**Comment by Haider8** [comment]
@Crouser Go ahead

**Comment by roshnet** [comment]
> @Haider8 i would like to worl on this issue.

Please `worl` on this.
