### ISSUE TITLE
Projects are ordered in opposite order

### ISSUE THREAD

**Issue by iamareebjamal** [open-roboclub/roboclub-vue#331]
Newer projects should be above

Please fix this ASAP

**Comment by iamareebjamal** [comment]
Hopefully @irfankhaan can do it by now. This is a small fix. If not, then @Haider8 please do it

**Comment by irfankhaan** [comment]
I can't! I don't understand the logic.

**Comment by iamareebjamal** [comment]
Till when will you understand it? It's almost end of summer vacations. Then college will open and you will have even less time
